[package]
name = "web-build"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[build-dependencies]
wasm-bindgen = "0.2"
controller = { path = "../../lib/controller" }
worker = { path = "../../lib/worker" }

